<a href="https://colab.research.google.com/github/Mayuri-dhane40/Letsupgrade_Data_Science/blob/main/Ass_3_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment Day 3 Data Science

Q.1

In [ ]:
import numpy as np

In [ ]:
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

Q.2

In [ ]:
import numpy as np
 
list1=[]
list2=[]
n=5
for i in range(0,n):
    ele=int(input("list1:"))
    list1.append(ele)
arr1=np.array(list1)  
for i in range(0,n):
    ele=int(input("list2:"))
    list2.append(ele)
arr2=np.array(list2)
 
arr=np.concatenate((arr1,arr2)) 
print(arr)
a=np.sort(arr)
print("sorting array",a)

list1:32
list1:12
list1:53
list1:98
list1:10
list2:46
list2:33
list2:34
list2:50
list2:22
[32 12 53 98 10 46 33 34 50 22]
sorting array [10 12 22 32 33 34 46 50 53 98]


Q.3

In [ ]:
import numpy as np
a1d = np.arange(3)
print("First array",a1d)
a2d = np.arange(12).reshape((3, 4))
print("Second array",a2d)
a3d = np.arange(24).reshape((2, 3, 4))
print("Third array",a3d)
print("Dimensions of numpy array") 
print(a1d.ndim)
print(a2d.ndim)
print(a3d.ndim)
print("Size of numpy array")
print(a1d.shape)
print(a2d.shape)
print(a3d.shape)

First array [0 1 2]
Second array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Third array [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Dimensions of numpy array
1
2
3
Size of numpy array
(3,)
(3, 4)
(2, 3, 4)


Q.4

In [ ]:
 
import numpy as np
 
a=np.array([10,20,30,40,50,60,70])
print(a.shape) 
b=a[np.newaxis, :]
print(b.shape) 
row_vector = a[np.newaxis, :]
print(row_vector.shape) 
col_vector = a[:, np.newaxis]
print(col_vector.shape) 
d= np.expand_dims(a, axis=1)
print(d.shape) 
print("2d array",b)

(7,)
(1, 7)
(1, 7)
(7, 1)
(7, 1)
2d array [[10 20 30 40 50 60 70]]


Q.5

In [ ]:
import numpy as np 
 
a = np.array([[1, 2], 
 
              [3, 4]])
b = np.array([[5, 6], 
 
              [7, 8]]) 
print("Vertically stacking",np.vstack((a,b))) 
print("Horizontally stacking",np.hstack((a,b)))

Vertically stacking [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally stacking [[1 2 5 6]
 [3 4 7 8]]


Q.6

In [ ]:
number_list = np.array([1, 1, 2, 3, 4, 4, 1])
 
(unique, counts) = np.unique(number_list, return_counts=True)
frequencies = np.asarray((unique, counts)).T
 
print(frequencies)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
